"""Constants for the Coronavirus Hessen integration."""
DOMAIN = "coronavirus_hessen"
ENDPOINT = "https://soziales.hessen.de/Corona/Bulletin/Tagesaktuelle-Zahlen"
ATTRIBUTION = "Data provided by Hessisches Ministerium für Soziales und Integration"
OPTION_TOTAL = "total"
